### ISSUE TITLE
How do I configure a push build in a Pull Request context? 

### ISSUE THREAD

**Issue by snackattas** [coverallsapp/coverage-reporter#113] opened 2024-02-26 16:04 UTC
### How do I configure a push build in a Pull Request context? 

https://docs.coveralls.io/build-types#recommended-ci-configurations

how would I implement this strategy with this tool? It seems there's no options to configure whether you want your upload to count as a pull request build or push build
<img width="679" alt="2024-02-26 10 03 47" src="https://github.com/coverallsapp/coverage-reporter/assets/12533693/b04c9b7b-af7e-4df2-a35c-35a412a79279">

**Comment by afinetooth** [comment] 2024-02-26 17:22
Hi @snackattas. I see your emails to support@coveralls.io as a paying subscriber so I will answer those as well, but I wanted to respond here as well:

> How do I configure a push build in a Pull Request context?
> https://docs.coveralls.io/build-types#recommended-ci-configurations

All you need to do is configure your CI service to send Coveralls coverage reports for `push` commits on your PR branches.

So using GitHub Actions as the example, that would look like this:

```
on:
  push:
```

Which just means build all `push` builds. You can further specify branch patterns is you have a known pattern for how you name PR branches.

Alternatively, you can build all `push` commits, and `pull_request` commits targeting your default branch (ex. `main`) like:

```
on:
  push:
  pull_request:
    branches:
      - main
```

**More info on how Coveralls handles `push` builds on your PR branches per our CI config recommendations**:

Since we started making changes to the way we handle ["drifted" pull request builds](https://docs.coveralls.io/build-types#common-issue-drifted-builds--two-dot-vs-three-dot-diff-comparisons-in-coverage-reports) in Coveralls (pull request builds whose base commit is no longer the head of the PR's target branch) in early Nov, we've changed the way Coveralls handles `push` builds that belong to PRs:

- We now treat any new `push` build that belongs to a PR as though it were the pull request build for the current head of your PR branch.
- We do this by checking each `push` build to see if it belongs to an open PR, and, if it does, we render it as such.
- But, we also send accompanying status updates to the relevant `push` commit at GitHub, and we include two different status updates to your PR (if status updates are enabled):
  - `coverage/coveralls (push)`
  - `coverage/coveralls (pull_request)`
- We do that so you can distinguish the coverage details for the `push` commit vs the coverage details for the PR at that point. 
- If you are also sending us coverage reports for `pull_request` builds on your PR branches, those will essentially be a duplicate of the build above, but those `pull_request` builds remain susceptible to becoming "drifted", whereas the pull request builds we derive from comparing the latest `push` commit on your PR branch with the PR's base commit (on your target branch) should be an accurate [three-dot-diff comparison](https://docs.coveralls.io/build-types#three-dot-diff-comparisons-accurate-pr-coverage-report), resulting in an accurate coverage report for your PR (at that point in time).

Sorry if I lost the thread in all those details. I though you might want to know the rest, once you learned that we are actually treating some of your `push` builds as though they were `pull_request` builds.

As I say, I will follow up in email, but let me know if, for yourself, or others who may be having the same issue, I can answer some more questions about your use case/

**Comment by snackattas** [comment] 2024-02-26 18:53
> Alternatively, you can build all push commits, and all pull_request commits targeting your default branch (ex. main) like this:

Hey @afinetooth , one thing is, I don't use github actions, I use Codefresh.

So how would I specify these configurations with just the coverage-reporter tool? That was one of my main points of confusion.

> But, we also send accompanying status updates to the relevant push commit at GitHub, and we include two different status updates to your PR (if status updates are enabled):
coverage/coveralls (push)
coverage/coveralls (pull_request)

On this point, I have been using the coverage-reporter, but only ever see pull_request builds posted back to the PR.

When my PR is merged into master, I have a job that runs the same CI unit tests/coverage reporter on master, and that posts back as a push build. 

But I have not seen the push build posted back to a PR. How do I get this to happen? I want that elusive 3 dot coverage 

> I though you might want to know the rest, once you learned that we are actually treating some of your push builds as though they were pull_request builds.

How can I tell if this is the case?

**Comment by afinetooth** [comment] 2024-02-26 19:59
> I don't use github actions, I use Codefresh.
>
> So how would I specify these configurations with just the coverage-reporter tool? That was one of my main points of confusion.

If you don't use Github Actions or CircleCI, then you'll want to bypass both of those official [extensions](https://docs.coveralls.io/integrations#official-integrations) for those services and use the [Universal Coverage Reporter](https://github.com/coverallsapp/coverage-reporter) directly.

These [usage examples](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#examples), plus [the section below it](https://github.com/coverallsapp/coverage-reporter?tab=readme-ov-file#examples:~:text=For%20more%20options%20see%20coveralls%20%2D%2Dhelp), with the output you'll see from invoking `coveralls --help` will show you the flag to use that are equivalent to the input options I've mentioned for the GitHub Action.

For general CI configuration, like telling your CI that you want to build `push` builds on your PR branches, that's something I don't have the expertise to give you, since it's based on Codefresh syntax. However, [this Codefresh doc](https://codefresh.io/docs/docs/ci-cd-guides/pull-request-branches/) seesm to suggest that that use case might be the default behavior of Codefresh:

> **Building branches automatically**
> By default, Codefresh connects to your Git provider and does the following:
>
> 1. Auto-builds every new commit that happens in master or any other branch
> 2. Auto-builds every new branch when it is created
> 
> You can change the default behavior so that it matches your own workflow using extra [Git triggers](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/).
>
> You don’t have to do anything special to set up this communication between Codefresh and your Git provider. It was set up automatically when you connected your Codefresh account to your Git provider.

And this section on [Git Triggers](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/) seems to document how to trigger Codefresh pipeline on `push` or `pull_request` events, which they list among their [git trigger events](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/).

To conform to our Recommended CI Config, "just build `push` commits on all branches," it looks like the relevant event is [Push commits](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/#:~:text=GitHub%20documentation.-,Push%20commits,-Push%20tags) (which also seems to be the default setup).

To also build on `pull_request` events, you probably, minimally, want to use the [Pull Request synchronized](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/#:~:text=Pull%20Request%20synchronized) trigger.

But again, you probably don't need to do that, and can probably see how it goes with just building all your `push` commits before adding more trigger events.

**Comment by afinetooth** [comment] 2024-02-26 20:11
> > But, we also send accompanying status updates to the relevant push commit at GitHub, and we include two different status updates to your PR (if status updates are enabled):
> > coverage/coveralls (push)
> > coverage/coveralls (pull_request)
> 
> On this point, I have been using the coverage-reporter, but only ever see pull_request builds posted back to the PR.

Can you please share the Coveralls Build URL for such as PR build? I can see what status updates we sent and how that aligns with your repos settings for status updates. Then we can determine if it's a config thing or a bug.

> When my PR is merged into master, I have a job that runs the same CI unit tests/coverage reporter on master, and that posts back as a push build.

That behavior, as described, is expected. After you merge a PR into `master`, it results in a new `push` commit on `master`, which, if you're building all `push` commits (Codefresh default behavior), and sending coverage reports for them to Coveralls, we'll have a new push build for you on master in Coveralls.

That's what you want, because if that commit becomes the merge base for a new PR, that coverage report (ie. Coveralls "base build") will be needed to calculate three-dot diffs with the new PR's HEAD commit(s).

> But I have not seen the push build posted back to a PR. How do I get this to happen? I want that elusive 3 dot coverage

That `push` build ( on `master`) does not get posted back to a PR. Because it's on `master` it's no longer associated with a pull request build, until such time as it _may_ become the base build of a new PR.

Rest assured that if you create a new PR from any `push` commit on `master`, Coveralls will look for that `push` commit's coverage report to compare it with the commits in your new PR.

So it is good, and correct, that you are building `push` commits on your `master` branch because any of those could become the "base build" for a new PR (Where "base build" is Coveralls parlance for the coverage report for those `push` commits).

**Comment by afinetooth** [comment] 2024-02-26 20:35
> > I though you might want to know the rest, once you learned that we are actually treating some of your push builds as though they were pull_request builds.
> 
> How can I tell if this is the case?

You can trust that we will generate a (Coveralls) pull request build for any coverage reports you send us for `push` commits that belong to any of your open PRs.

But you can verify that by following the link in your CI build log to the new job or build at Coveralls and reviewing the build.

I don't want to use one of your builds as an example since your repos are private, but using one of our PRs for Coveralls:

These are our **Repo Settings**:

<img width="753" alt="Screenshot 2024-02-26 at 12 17 44 PM" src="https://github.com/coverallsapp/coverage-reporter/assets/918667/33ba0185-1fa4-4438-b4b5-c770f08a9af5">

And these are the **status updates** we receive as a result:

![screencapture-github-coverallsapp-coveralls-pull-2142-2024-02-26-12_16_15](https://github.com/coverallsapp/coverage-reporter/assets/918667/14a4f8af-a662-4a85-80b8-a58d6874e175)

I am primarily focusing here on the difference between the **`push` commit status update**, and the **`pull_request` status update**:

1. We send a status update for each `push` commit for which we've received a coverage report.
2. Since that `push` commit is part of an open pull request, we also generate a coverage report for the PR and send a status update for the `pull_request` (even though we don't need you to send us a coverage report for the `pull_request` commit, which could be faulty/[drifted](https://docs.coveralls.io/build-types#common-issue-drifted-builds--two-dot-vs-three-dot-diff-comparisons-in-coverage-reports) anyway). We derive the pull request coverage details from doing a **coverage diff** between the coverage report for the latest `push` commit in the PR (PR HEAD) and the coverage report for the `push` commit on `master` that is the PR's base commit.

Hope that makes sense.

If you configure your status updates something like ours, you should get similar results.

**Closed** 2024-02-27 19:52 UTC
Labels: feature request
